# Generated by Django 5.2.11 on 2026-04-17 16:36

import apps.documents.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500, verbose_name="Título")),
                (
                    "year",
                    models.IntegerField(blank=True, null=True, verbose_name="Año"),
                ),
                (
                    "author",
                    models.CharField(blank=True, max_length=300, verbose_name="Autor"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[("printed", "Impreso"), ("manuscript", "Manuscrito")],
                        default="printed",
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(default=True, verbose_name="Público"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("total_views", models.PositiveIntegerField(default=0)),
                ("total_downloads", models.PositiveIntegerField(default=0)),
                ("total_edits", models.PositiveIntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_documents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "last_modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="modified_documents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Última modificación por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento",
                "verbose_name_plural": "Documentos",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OperationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("insert_doc", "Inserción de documento"),
                            ("edit_doc", "Edición de documento"),
                            ("view_doc", "Visualización de documento"),
                            ("download_doc", "Descarga de documento"),
                            ("insert_user", "Inserción de usuario"),
                            ("remove_user", "Eliminación de usuario"),
                            ("edit_privileges", "Edición de privilegios"),
                            ("login", "Inicio de sesión"),
                            ("logout", "Cierre de sesión"),
                        ],
                        max_length=30,
                        verbose_name="Acción",
                    ),
                ),
                ("description", models.TextField(verbose_name="Descripción")),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha y hora"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de operación",
                "verbose_name_plural": "Registros de operaciones",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(verbose_name="Orden")),
                (
                    "image",
                    models.ImageField(
                        upload_to=apps.documents.models.page_image_path,
                        verbose_name="Facsimilar",
                    ),
                ),
                ("text", models.TextField(blank=True, verbose_name="Texto transcrito")),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pages",
                        to="documents.document",
                    ),
                ),
            ],
            options={
                "verbose_name": "Página",
                "verbose_name_plural": "Páginas",
                "ordering": ["order"],
                "unique_together": {("document", "order")},
            },
        ),
    ]
