# Generated by Django 5.2.11 on 2026-04-17 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operationlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("insert_doc", "Inserción de documento"),
                    ("edit_doc", "Edición de documento"),
                    ("view_doc", "Visualización de documento"),
                    ("download_doc", "Descarga de documento"),
                    ("insert_user", "Inserción de usuario"),
                    ("remove_user", "Eliminación de usuario"),
                    ("edit_privileges", "Edición de privilegios"),
                    ("login", "Inicio de sesión"),
                    ("logout", "Cierre de sesión"),
                    ("delete_doc", "Eliminación de documento"),
                ],
                max_length=30,
                verbose_name="Acción",
            ),
        ),
    ]
